import { Download } from 'lucide-react';
import type { Currency, TradeAction, TradeRow } from '../types/portfolio';
import { formatMoney, formatNumber, formatPercent } from '../lib/currency';

const ACTION_LABELS: Record<TradeAction, string> = { BUY: 'AL', SELL: 'SAT', SELL_ALL: 'TAMAMINI SAT', BUY_NEW: 'YENİ ALIM', HOLD: 'TUT', MISSING_PRICE: 'FİYAT EKSİK' };

export function TradeTable({ trades, currency, onDownloadCsv }: { trades: TradeRow[]; currency: Currency; onDownloadCsv: () => void }) {
  const headers = ['Sembol', 'Piyasa', 'Mevcut lot', 'Hedef lot', 'İşlem', 'Lot farkı', 'Fiyat', 'Tahmini tutar', 'Mevcut ağırlık', 'Hedef ağırlık', 'Fark', 'Not'];
  return <section className="rounded-lg border border-zinc-200 bg-white p-4 shadow-soft dark:border-zinc-800 dark:bg-zinc-950"><div className="mb-4 flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-lg font-semibold">Al/Sat Emir Tablosu</h2><p className="text-sm text-zinc-500">Emir göndermez; sadece matematiksel işlem listesi üretir.</p></div><button className="inline-flex items-center gap-2 rounded-md bg-teal-600 px-3 py-2 text-sm font-semibold text-white" type="button" onClick={onDownloadCsv}><Download className="h-4 w-4" />CSV indir</button></div><div className="overflow-x-auto"><table className="min-w-[1200px] w-full border-separate border-spacing-0 text-left text-sm"><thead><tr className="text-xs uppercase text-zinc-500">{headers.map((header) => <th className="border-b border-zinc-200 pb-2 pr-3 dark:border-zinc-800" key={header}>{header}</th>)}</tr></thead><tbody>{trades.length === 0 ? <tr><td className="py-6 text-center text-zinc-500" colSpan={12}>Mevcut ve hedef portföy girildiğinde işlem tablosu oluşur.</td></tr> : trades.map((trade) => <tr key={trade.key}><td className="border-b border-zinc-100 py-3 pr-3 font-semibold dark:border-zinc-900">{trade.symbol}</td><td className="border-b border-zinc-100 py-3 pr-3 dark:border-zinc-900">{trade.market}</td><td className="border-b border-zinc-100 py-3 pr-3 dark:border-zinc-900">{formatNumber(trade.currentQuantity, 4)}</td><td className="border-b border-zinc-100 py-3 pr-3 dark:border-zinc-900">{formatNumber(trade.targetQuantity, 4)}</td><td className="border-b border-zinc-100 py-3 pr-3 dark:border-zinc-900"><span className={actionClass(trade.action)}>{ACTION_LABELS[trade.action]}</span></td><td className="border-b border-zinc-100 py-3 pr-3 dark:border-zinc-900">{formatNumber(trade.quantityDiff, 4)}</td><td className="border-b border-zinc-100 py-3 pr-3 dark:border-zinc-900">{trade.displayPrice ? formatMoney(trade.displayPrice, trade.priceCurrency) : '-'}</td><td className="border-b border-zinc-100 py-3 pr-3 dark:border-zinc-900">{formatMoney(trade.estimatedAmount, currency)}</td><td className="border-b border-zinc-100 py-3 pr-3 dark:border-zinc-900">{formatPercent(trade.currentWeight, 2)}</td><td className="border-b border-zinc-100 py-3 pr-3 dark:border-zinc-900">{formatPercent(trade.targetWeight, 2)}</td><td className="border-b border-zinc-100 py-3 pr-3 dark:border-zinc-900">{formatPercent(trade.weightDiff, 2)}</td><td className="max-w-xs border-b border-zinc-100 py-3 pr-3 text-zinc-600 dark:border-zinc-900 dark:text-zinc-300">{trade.note}</td></tr>)}</tbody></table></div></section>;
}

function actionClass(action: TradeAction): string {
  const base = 'inline-flex rounded-md px-2 py-1 text-xs font-semibold';
  if (action === 'BUY' || action === 'BUY_NEW') return `${base} bg-emerald-100 text-emerald-700 dark:bg-emerald-950/40 dark:text-emerald-300`;
  if (action === 'SELL' || action === 'SELL_ALL') return `${base} bg-rose-100 text-rose-700 dark:bg-rose-950/40 dark:text-rose-300`;
  if (action === 'MISSING_PRICE') return `${base} bg-amber-100 text-amber-700 dark:bg-amber-950/40 dark:text-amber-300`;
  return `${base} bg-zinc-100 text-zinc-700 dark:bg-zinc-800 dark:text-zinc-200`;
}
